console.log("=========================================================");
console.log("Segunda-feira ");
console.log("Saudação do puxa saco! ");
console.log("Bom dia ");
console.log("Boa tarde ");
console.log("Boa noite ");
console.log("=========================================================");
console.log("=========================================================");
console.log("Terça-feira ");
console.log("Saudação do puxa saco! ");
console.log("Bom dia ");
console.log("Boa tarde ");
console.log("Boa noite ");
console.log("=========================================================");
console.log("=========================================================");
console.log("Quarta-feira ");
console.log("Saudação do puxa saco! ");
console.log("Bom dia ");
console.log("Boa tarde ");
console.log("Boa noite ");
console.log("=========================================================");
console.log("=========================================================");
console.log("Quinta-feira ");
console.log("Saudação do puxa saco! ");
console.log("Bom dia ");
console.log("Boa tarde ");
console.log("Boa noite ");
console.log("=========================================================");
console.log("=========================================================");
console.log("Sexta-feira ");
console.log("Saudação do puxa saco! ");
console.log("Bom dia ");
console.log("Boa tarde ");
console.log("Boa noite ");
console.log("=========================================================");
console.log("=========================================================");
console.log("Sábado ");
console.log("Saudação do puxa saco! ");
console.log("Bom dia ");
console.log("Boa tarde ");
console.log("Boa noite ");
console.log("=========================================================");
console.log("=========================================================");
console.log("Domingo ");
console.log("Saudação do puxa saco! ");
console.log("Bom dia ");
console.log("Boa tarde ");
console.log("Boa noite ");
console.log("=========================================================");